### ISSUE TITLE
How stop playerManager from other ViewController?

### ISSUE THREAD

**Issue by mehdin13** [FoksWang/FWPlayer#1]
Can stop the player from another controller?
because when I use PlayerOverlayVideoVC.shared.playerManager.isPlaying its always return nil.

**Comment by FoksWang** [comment]
1. FWAVPlayerManager will be handled by FWPlayerController internally.
2. If you are using customized `playerManager`, please conform `FWPlayerMediaPlayback`, and handle `isPlaying` by yourself.

See more in the `Normal Style` parts of README, usage with Swift.
