### ISSUE TITLE
Add option header in AVURLAsset?

### ISSUE THREAD

**Issue by rafsanahmad** [FoksWang/FWPlayer#10]
HI,

Great library for video playing.

I have a question regarding setting the assetUrl in `FWPlayerController`.

Is there a way to add custom header in the asset url?

For example: In `Avplayer` we can add `AVURLAssetHTTPHeaderFieldsKey` using `AVURLAsset`.
```
let url = URL(string: "url")
let asset = AVURLAsset(url: url!, options: ["AVURLAssetHTTPHeaderFieldsKey" : [ "Cookie" : "tx=\(some_value)" ] ])
let PlayerItem = AVPlayerItem(asset: asset)
let player = AVPlayer(playerItem: PlayerItem)
```

**Comment by FoksWang** [comment]
Hi,

Regarding the custom header, you can set it like this:
`playerManager.requestHeader = ["AVURLAssetHTTPHeaderFieldsKey": ["Cookie": "tx=\(some_value)"]]`

Thank you for you like this library.

**Comment by rafsanahmad** [comment]
Thanks, it works.
