### ISSUE TITLE
Customize player control

### ISSUE THREAD

**Issue by rafsanahmad** [FoksWang/FWPlayer#11]
Hi,

I have a couple of questions, with regards to configuring the player control view with custom icon, color, etc..

a) Currently the player control displays the download information like - 40Kb/s - Is there any way to disable that?
![image](https://user-images.githubusercontent.com/19227159/117568556-c3dbee00-b0e2-11eb-925b-c40fcce3c97b.png)

b) How to show a volume button on player control (without opening full screen)?
![image](https://user-images.githubusercontent.com/19227159/117568560-c6d6de80-b0e2-11eb-9045-893f54f6bf92.png)

c) How can I change the player slider color & custom icon for full-screen?

Thanks.

**Comment by FoksWang** [comment]
**Network speed monitor** and **slider** color is `readonly` in `FWPlayerControlView`, so you cannot change them.

However, you can create your own player control view by just create a `UIView` that inherits the protocol `FWPlayerMediaControl`.
