### ISSUE TITLE
[BUG] Audio session is being configured regardless

### ISSUE THREAD

**Issue by Ludotrico** [FoksWang/FWPlayer#13]
Although I marked customAudioSesson = true, the library is **still configuring** the shared audio session. This is messing with the audio session and bugging other parts of my app. Why is this occurring?

Separate topic: why is the source code all executable? How can I change parts of the library?

**Comment by Ludotrico** [comment]
Although I marked customAudioSesson = true, the library is messing with the audio session and bugging other parts of my app.

**Comment by FoksWang** [comment]
I just checked the source code, I can confirm that `customAudioSession` is fine.

The logic to set `customAudioSession` is like this:

```swift
FWPlayerController ->

- (void)setCurrentPlayerManager:(id<FWPlayerMediaPlayback>)currentPlayerManager ->

self.currentPlayerManager.playerReadyToPlay = ^(id<FWPlayerMediaPlayback> _Nonnull asset, NSURL * _Nonnull assetURL) {
    @strongify(self)
    if (self.playerReadyToPlay) self.playerReadyToPlay(asset,assetURL);
    if (!self.customAudioSession) {
        // Apps using this category don't mute when the phone's mute button is turned on, but play sound when the phone is silent
//            [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback withOptions:AVAudioSessionCategoryOptionAllowBluetooth error:nil];
        [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil];
        [[AVAudioSession sharedInstance] setActive:YES error:nil];
    }
    if (self.viewControllerDisappear) self.pauseByEvent = YES;
};
```

Hope it helps!

**Comment by Ludotrico** [comment]
@FoksWang Thank you for your quick response. After trying tons of combinations of settings, for some reason I got it to work doing the following:

**FWAVPlayerManager.isPlaySoundInSilentMode = NO;  <----- this fixed everything**
FWPlayerController.customAudioSession = YES;
