### ISSUE TITLE
Add sub view to player

### ISSUE THREAD

**Issue by HosseinArabbeigi** [FoksWang/FWPlayer#2]
Thanks @FoksWang  for amazing video player, good job!

How can is add a subview to player? I need to have a watermark in fullscreen mode.

**Comment by FoksWang** [comment]
Hi, this library does not have a watermark function. However, you can try to add your own watermark view to `FWPlayerControlView`, or make a customized player view and conform to the `FWPlayerMediaControl` protocol.

**Comment by HosseinArabbeigi** [comment]
Thanks.
