### ISSUE TITLE
Placeholder issue

### ISSUE THREAD

**Issue by ShubhamSingla125** [FoksWang/FWPlayer#3]
@FoksWang 
After adding the image view as a container view in the player controller. It's not showing the placeholder image just showing the black color when the video is stopped.

self.player = FWPlayerController(playerManager: playerManager, containerView: self.videoImgVw)

**Comment by FoksWang** [comment]
Right, the placeholder is a video cover just displayed before playback.

**Comment by ShubhamSingla125** [comment]
So how I can handle this. Need to show the placeholder when the video is stopped.

**Comment by FoksWang** [comment]
Are you using custom `controlView` or default?

**Comment by ShubhamSingla125** [comment]
This is fixed. I am placing a placeholder when the video is ready to play then hide the placeholder.

**Comment by ShubhamSingla125** [comment]
@FoksWang I have one more question. How we can mute the video player audio?

**Comment by FoksWang** [comment]
if you are using `FWPlayerMediaPlayback`, you can use `muted` to control.

otherwise, you can control it like below:
```
self.player = FWPlayerController(playerManager: playerManager, containerView: self.containerView)
playerManager.isMuted = true
```

**Comment by ShubhamSingla125** [comment]
@FoksWang Thanks for the reply. 
How we can handle the speed rate playback (0.5x, 1.0x, 1.25x, 1.5x, 2.0x)?

**Comment by ShubhamSingla125** [comment]
@FoksWang After changing the playback speed rate How we can get that video?

**Comment by ShubhamSingla125** [comment]
@FoksWang Can we add filters in the video?

**Comment by FoksWang** [comment]
could you close this issue and open another one?
