### ISSUE TITLE
Status Bar issue 

### ISSUE THREAD

**Issue by Issam-Otoz** [FoksWang/FWPlayer#4]
@FoksWang 
first of all Thank you for this library 
after I have installed the FWPlayer from pod {pod 'FWPlayer', '~> 1.0.13'}
the status-bar become white always ,
how can I stop the library from control for status bar color because I have two theme (two mode) on my app (dark and light mode) ,
before install FWPlayer everything's fine , but after install it I have this issue 
[Before](https://ibb.co/WyCNG0v) , [After](https://ibb.co/PFRPdK5)

**Comment by Issam-Otoz** [comment]
the problem has been resolved :
I have put :
override var preferredStatusBarStyle: UIStatusBarStyle {
        Theme.shared.isLight() ? .default : .lightContent
    }
in Base ViewController

**Comment by FoksWang** [comment]
Glad to hear that you have solved the issue!
It is correct to put your code under method `preferredStatusBarStyle`.
