### ISSUE TITLE
How to place controlView inside the safe area

### ISSUE THREAD

**Issue by Gyoutou** [FoksWang/FWPlayer#7]
Hello Mr. Wang

FWPlayer SDK is great, Our team want to include into our vlog project.
But in my project, the controlView is displayed out than safe area.
Ps: The example is work well.

IOS Target: `14.0`

![image](https://user-images.githubusercontent.com/10691259/108543146-04b83800-7328-11eb-8ed2-19f723640149.png)

Can you help me? 
Thanks in advance!

**Comment by FoksWang** [comment]
Ha, I can see the `controlView` is fine, but you have a blurred background.

Below is the example running on iPhone 12, iOS 14.4.
![image](https://user-images.githubusercontent.com/2570793/109413929-5314a900-79b0-11eb-9ba0-436ae19a5a57.png)

**Comment by Gyoutou** [comment]
Hello Mr. FoksWang
Thanks for the reply

The problem maybe our team only allow `Device Orientation` set as `Portrait` at `.xcodeproj`.
Without modify xcodeproj file, I reCalc `controlView` frame size to fit the screen.
```swift
player?.orientationDidChanged = { [unowned self] (player, isFullScreen) in
    let width = max(UIScreen.main.bounds.width, UIScreen.main.bounds.height)
    let height = min(UIScreen.main.bounds.width, UIScreen.main.bounds.height)
    if isFullScreen {
        player.controlView.bounds = CGRect(x: statusBarHeight, y: 0.0, width: width - statusBarHeight, height: height)
    } else {
        player.controlView.bounds = CGRect(x: 0.0, y: 0.0, width: height, height: height * 9 / 16)
    }
}
```
Now it's worked.

**Comment by FoksWang** [comment]
Nice to hear that you have solved the issue!
