### ISSUE TITLE
unrecognized selector sent to instance error

### ISSUE THREAD

**Issue by M0TRIX** [FoksWang/FWPlayer#8]
```

import UIKit
import FWPlayerCore

class ViewController: UIViewController {
    
    private var player: FWPlayerController?
    let playerManager = FWAVPlayerManager()
    
    @IBOutlet weak var containerView:UIImageView!
    //@IBOutlet weak var containerView:UIImageView!
    
    @IBOutlet weak var controlView: FWPlayerControlView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        controlView.fastViewAnimated = true
        controlView.autoHiddenTimeInterval = 5.0
        controlView.autoFadeTimeInterval = 0.5
        controlView.prepareShowLoading = true
        controlView.prepareShowControlView = true
        
        playerManager.isEnableMediaCache = false
        
    
    }
    
    @IBAction func button(_ sender: Any) {
        // Setup player
            self.player = FWPlayerController(playerManager: playerManager, containerView: self.containerView)
            self.player?.controlView = self.controlView
            
            // Setup continue playing in the background
            self.player?.pauseWhenAppResignActive = true
            
            self.player?.orientationWillChange = { [weak self] (player, isFullScreen) in
                self?.setNeedsStatusBarAppearanceUpdate()
            }
            
            // Finished playing
            self.player?.playerDidToEnd = { [weak self] (asset) in
                guard let strongSelf = self else {
                    return
                }
                strongSelf.player?.currentPlayerManager.replay!()
                strongSelf.player?.playTheNext()
                if strongSelf.player?.isLastAssetURL == false {
                    strongSelf.controlView.showTitle("Video Title", coverURLString: nil, fullScreenMode: .landscape)
                } else {
                    strongSelf.player?.stop()
                }
            }
            
            var urls = [URL]()
        guard let url = URL(string: "https://www.radiantmediaplayer.com/media/big-buck-bunny-360p.mp4") else { return }
        urls.append(url)
        print(urls)
        self.player?.assetURLs = urls
            
    }
}

```

lovely player but i coudn't use it as well. will you help me ?

**Comment by M0TRIX** [comment]
how can i play my urls ?

**Comment by FoksWang** [comment]
Hi, I just updated README, added a quick demo for playback in the normal style, hope it helps, please check.
https://github.com/FoksWang/FWPlayer#quick-demo-for-normal-style

**Comment by M0TRIX** [comment]
crashing in 

 @IBAction func playButtonClick() {
        print("playButtonClick")
        self.player!.playTheIndex(assetIndex)
        self.controlView.showTitle("Video title 1", coverURLString: kVideoCover, fullScreenMode: .automatic)
    }

**Comment by M0TRIX** [comment]
thank you for replaying..... :x

**Comment by FoksWang** [comment]
...
`@IBAction func playButtonClick()` comes from a storyboard, you can replace it with your button, and I can fix it later.

**Comment by FoksWang** [comment]
...
`@IBAction func playButtonClick()` comes from a storyboard, you can replace it with your button, and I can fix it later.

**Comment by FoksWang** [comment]
"Quick demo for Normal Style" has updated, thank you for your report!

**Comment by M0TRIX** [comment]
crashing again ....

**Comment by FoksWang** [comment]
`Quick demo for Normal Style` like its name, it is a quick demo.
Since the player compatible with iOS 10 and above, you need to make sure you have `window` in both `AppDelegate` and `SceneDelegate`
I will maybe need to upload more sample code to README...

**Comment by FoksWang** [comment]
README has been updated, please check.

**Comment by M0TRIX** [comment]
finally, I could run the app  :D

but still, there are problems, have you tested full-screen mode? freezes the app.

 and there is no forward and previous button.....

**Comment by FoksWang** [comment]
no, there are no forward and previous buttons, you can swipe on the screen to get that. you also can implement your own `controlview` if you like.

Please read the README, watch the demo video, and try the demo app by yourself. (`Quick demo for Normal Style` is just a simple and quick look)
