### ISSUE TITLE
Laggy video on iPhone 8

### ISSUE THREAD

**Issue by MohsenKhosravinia** [FoksWang/FWPlayer#9]
There is some lags in iPhone 8 (iOS 14.2) when a video plays for the first time. I think you should set the 'automaticallyWaitsToMinimizeStalling' if it is not. The caching process is helping me so much so if you help me on this issue too that would be wonderful.

**Comment by FoksWang** [comment]
Hi, the initialization of the player includes:
`if (@available(iOS 10.0, *)) {
         _playerItem.preferredForwardBufferDuration = 5;
         _player.automaticallyWaitsToMinimizeStalling = NO;
  }`

**Comment by MohsenKhosravinia** [comment]
I should call `playerManager.playerItem.preferredForwardBufferDuration` and `playerManager.player.automaticallyWaitsToMinimizeStalling` because those properties (playerItem and player) are not exposed by the framework.
